# Ubuntu. /: 28 (default), /mnt: 12
# Windows. c: 8.7, d:12.2 (default)
# McOS 10.14: /112Gb

variables:
  BENCHMARK_DURATION: Release # Either Release | Short
  NET_VER: net462

jobs:
  - job: Xenial_LLVM_9
    variables:
      OS: Linux
      LLVM: 9
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Xenial_LLVM_9_MONO_660
    variables:
      OS: Linux
      LLVM: 9
      NET_VER: net47
      MONO_VER: 6.6.0
    timeoutInMinutes: 119
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Xenial_LLVM_9_MONO_5_20_1
    variables:
      OS: Linux
      LLVM: 9
      NET_VER: net462
      MONO_VER: 5.20.1
    timeoutInMinutes: 199
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Xenial_LLVM_9_PLUS_AOT
    variables:
      OS: Linux
      LLVM: 9
      PLUS_AOT: 'true'
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Xenial_LLVM_8
    variables:
      OS: Linux
      LLVM: 8
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Xenial_LLVM_10
    variables:
      OS: Linux
      LLVM: 10
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Bionic_LLVM_8
    variables:
      OS: Linux
      LLVM: 8
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Bionic_LLVM_9
    variables:
      OS: Linux
      LLVM: 9
    timeoutInMinutes: 599
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml


trigger:
- master
