# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:

  - job: Ubuntu_Latest
    variables:
      OS: Linux
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - template: Benchmark-Strings-nix.yml


  - job: WIN_Latest
    variables:
      OS: Windows
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'windows-latest'
    steps:
      - template: Benchmark-Strings-nix.yml


  - job: MacOS_Latest
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'macOS-latest'
    steps:
      - template: Benchmark-Strings-nix.yml


