# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
     cat /etc/*release
     sudo apt-get update; sudo apt-get install tree -y
     
  displayName: 'configure'

- bash: |
     cat /etc/*release
     cd BenchmarkStrings 
     dotnet restore || dotnet restore --disable-parallel
     nuget resore
     msbuild /t:restore
     dotnet build -c Release
     tree -hu
     cd BenchmarkStrings/BenchmarkStrings/bin/Release/net47
     mono BenchmarkStrings.exe 
     
  displayName: 'Benchmark'

